### ISSUE TITLE
With the latest flatten js version my tests are breaking

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [alexbol99/flatten-js#192]
Current version used - ```
"node_modules/@flatten-js/core": {
            "version": "1.6.1",
```

Code was working with old versions -
Kindly help.
  
● line intersect polygon

    TypeError: edge.shape.reverse is not a function

      225 |     const ml = new Multiline([horizontalLine]).split(sortedIntersectionPoints)
      226 |
    > 227 |     const [p0, p1] = facePoly.cut(ml)
          |                               ^
      228 |
      229 |     expect(p0.area()).toBeCloseTo(p1.area())
      230 | })

      at node_modules/@flatten-js/core/dist/main.cjs:8092:87
          at Array.map (<anonymous>)
      at Polygon.cut (node_modules/@flatten-js/core/dist/main.cjs:8092:47)
      at Object.<anonymous> (src/modeler/geometry/__tests__/polygon.js:227:31)

  ● cut

    TypeError: edge.shape.reverse is not a function

      744 |         const ml = new Multiline([cuttingLine]).split(sortedIntersectionPoints)
      745 |
    > 746 |         const newPolygons = facePoly.cut(ml)
          |                                      ^
      747 |         // remove once we have caching in place...

**Comment by Neeraj-swarnkar** [comment]
@alexbol99, kindly help.

**Comment by Neeraj-Swarnkar-EV** [comment]
Hi @alexbol99, Any input on this issue ? Unit test work fine For version "1.4.8" but for above version it's not working.

**Comment by Neeraj-Swarnkar-EV** [comment]
Hi @alexbol99, Could you be able to help me ?

**Comment by alexbol99** [comment]
Hi, @Neeraj-swarnkar ,

Sorry for delay with my answer.

Usage of *polygon.cut()* method was changed, try this way:
```javascript
const ml = new Multiline([cuttingLine])
const resPolygon = facePoly.cut(ml)
```
This function returns single polygon which may have many faces. It was wrong to return two polygons.

You can also use simplified version *polygon.cutWithLine()*:
```javascript
let resPolygon = poly.cutWithLine(l);
```
