### ISSUE TITLE
Infinite loop for boolean union over (valid) polygons.

### ISSUE THREAD

**Issue by OliverColeman** [alexbol99/flatten-js#53]
I found two polygons for which a union operation causes an infinite loop. I did some digging and tracked it down to an apparently infinite CircularLinkedList. I put a limit on the number of iterations in CircularLinkedList and made it throw an exception when it exceeds 1,000,000 iterations, which then gives me this stack trace when I run the unify function in a test:
```
     Error: CircularLinkedList iteration exceeded limit.
      at Object.next (src/data_structures/circular_linked_list.js:29:25)                                                                                                                                          
      at Face.setArcLength (src/classes/face.js:281:9)                                                                                                                                                            
      at new Face (src/classes/face.js:130:18)                                                                                                                                                                    
      at Polygon.addFace (src/classes/polygon.js:146:17)                                                                                                                                                          
      at restoreFaces (src/algorithms/boolean_op.js:755:28)                                                                                                                                                       
      at swapLinksAndRestore (src/algorithms/boolean_op.js:174:5)                                                                                                                                                 
      at booleanOpBinary (src/algorithms/boolean_op.js:204:9)                                                                                                                                                     
      at unify (src/algorithms/boolean_op.js:30:32)                                                                                                                                                               
      at Context.<anonymous> (test/algorithms/boolean_op.js:636:33)                                                                                                                                               
      at processImmediate (internal/timers.js:456:21)
```
The changed iterator function is:
```
    [Symbol.iterator]() {
        let element = undefined;
        let count = 0;
        return {
            next: () => {
                let value = element ? element : this.first;
                let done = this.first ? (element ? element === this.first : false) : true;
                element = value ? value.next : undefined;
                count++;
                if (count > 1000000) {
                    throw Error("CircularLinkedList iteration exceeded limit.")
                }
                return {value: value, done: done};
            }
        };
    };
```
The test I ran is:
```
import { infiniteLoopPolygons}  from './boolean_op_data';
const polygons = infiniteLoopPolygons.map(p => new Polygon(p));
const result = unify(...polygons);
```
The polygons are attached.
[boolean_op_data.zip](https://github.com/alexbol99/flatten-js/files/5039703/boolean_op_data.zip)

**Comment by alexbol99** [comment]
Hello @OliverColeman 

Thank you for submitting the issue.
I am able to reproduce the problem, you will get update soon

Alex Bol

**Comment by alexbol99** [comment]
Hello @OliverColeman 

Bug fixed in release v1.2.10.
You can see it working in https://observablehq.com/d/fc9314e49d531cc7

Thank you for cooperation,
Alex Bol

**Comment by alexbol99** [comment]
Hi @OliverColeman,

I have a question for you.
Your data seems like you cleaned up self-intersecting poilygons.
Which tool did you use for that?

![issue_53](https://user-images.githubusercontent.com/6965440/89726235-e2f90280-da20-11ea-9c12-d042947399c6.png)

Thanks,
Alex

**Comment by OliverColeman** [comment]
Hi Alex,

Wow thanks for the quick turn-around time! 

To answer your question, I'm not using any tools for cleaning up self-intersecting polygons. The polygons here are a result of performing intersection operations (using flatten) on combinations of manually created polygons.

Cheers,
Oliver

**Comment by alexbol99** [comment]
Hi Oliver,

You are welcome :)
Keep playing around with flatten-js and feel free to report any problems you find

Best,
Alex
